<div class="circle" id="B">B</div>
            <div class="circle" id="E">E</div>
            <div class="circle" id="I">I</div>
            <div class="circle" id="A">A</div>
            <div class="circle" id="C">C</div>
            <div class="circle" id="D">D</div>
            <div class="circle" id="F">F</div>
            <div class="circle" id="G">G</div>
            <div class="circle" id="H">H</div>
            <div class="circle" id="J">J</div>
            <div class="circle" id="K">K</div>